### ISSUE TITLE
"IndexError: list index out of range"

### ISSUE THREAD

**Issue by ojaksch** [phoerious/massengeschmack-xbmc#13]
I don't know wether this is really a bug or a problem occuring on my site only.
Starting this plugins works and it logs into massengeschmack.tv. But when selecting a cathergory and then a subcathergory kodi's log throws a

> 11:13:08.106 T:139834941241088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>      Error Type: <type 'exceptions.IndexError'>
>      Error Contents: list index out of range
>      Traceback (most recent call last):
>           File "/home/larry/.kodi/addons/plugin.video.massengeschmack/default.py", line 45, in <module>
>                if listing.generate(datasource):
>           File "/home/larry/.kodi/addons/plugin.video.massengeschmack/resources/lib/listing.py", line 46, in generate
>                for i in items:
>           File "/home/larry/.kodi/addons/plugin.video.massengeschmack/resources/lib/datasource.py", line 296, in getListItems
>                data        = resources.lib.parseRSSFeed(self.buildFeedURL(submodule, self.getQuality(), currentPage), True)
>           File "/home/larry/.kodi/addons/plugin.video.massengeschmack/resources/lib/__init__.py", line 286, in parseRSSFeed
>                'subtitle'    : parser.unescape(node.getElementsByTagName('itunes:subtitle')[0].firstChild.nodeValue).encode('utf-8'),
>      IndexError: list index out of range
>      -->End of Python script error report<--
> 11:13:08.140 T:139837255962880   ERROR: GetDirectory - Error getting plugin://plugin.video.massengeschmack/?cmd=list&module=fktv&submodule=episodes
> 11:13:08.143 T:139837255962880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.massengeschmack/?cmd=list&module=fktv&submodule=episodes) failed

The plugin still works when selecting "latest releases".
Tested on one box with LibreElec and on another normal Linux with kodi poackage.

**Comment by phoerious** [comment]
Hmm. Looks like the itunes:subtitle tag is missing somewhere.

**Comment by ojaksch** [comment]
Can confirm that it's working again. Thank you!
