### ISSUE TITLE
Addon always returns to mainpage

### ISSUE THREAD

**Issue by mase76** [phoerious/massengeschmack-xbmc#14]
Hi!
I am running the Kodi master branch built on Debian Buster. The addon is also from master.
But the addon does not run anymore. It always returns back to the addon main page, no matter, which entry I choose. Nothing to see in the log. When entering the addon, I see, that I get logged in, but no sub pages.

**Comment by phoerious** [comment]
I'll have to check.

**Comment by phoerious** [comment]
Please update the Add-on version. I couldn't reproduce the problem with the new version. It was probably related to a change in the Feeds which has been fixed already.

**Comment by mase76** [comment]
I used the latest Git checkout.

**Comment by phoerious** [comment]
I can't reproduce it. Could you please have a look if there is an error message in your kodi log file?

**Comment by mase76** [comment]
I checked out again. Works now.
